/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  coursework: [
    'index',
    {
      type: `category`,
      label: `🧪 Labs`,
      collapsed: true,
      link: {
        type: `doc`,
        id: `labs`
      },
      items:[
        'labs/hello-world/index',
        {
          type: "category",
          label: "JS and DOM",
          link: {
            type: "doc",
            id: "labs/js-and-dom-exercises/index"
          },
          items: [
            {
              type: "autogenerated",
              dirName: "labs/2.js-and-dom-exercises",
            }
          ],
        },
        {
          type: "category",
          label: "Chatting App",
          link: {
            type: "doc",
            id: "labs/chatting-app/index"
          },
          items: [
            {
              type: "autogenerated",
              dirName: "labs/3.chatting-app",
            }
          ],
        },
        // 'labs/tooling/index',
        // 'labs/rps-in-react/index',
      ]
    },
    {
      type: `category`,
      label: `💯 Assignments`,
      collapsed: true,
      link: {
        type: `doc`,
        id: `assignments`
      },
      items:[
        {
          type: "autogenerated",
          dirName: "assignments",
        },
        // {
        //   type: "category",
        //   label: "Online Portfolio",
        //   link: {
        //     type: `doc`,
        //     id: `assignments/online-portfolio/index`
        //   },
        //   items: [
        //     `assignments/online-portfolio/index`,
        //     `assignments/online-portfolio/part1`,
        //     `assignments/online-portfolio/part2`,
        //     `assignments/online-portfolio/finalize`,
        //   ],
        // },
        // {
        //   type: "category",
        //   label: "JS Exercises",
        //   items: [
        //     {
        //       type: "autogenerated",
        //       dirName: "assignments/2.js-exercises",
        //     }
        //   ],
        // },
        // 'assignments/rock-paper-scissors/index',
        // 'assignments/hangman/index',
      ]
    }
  ]
};

module.exports = sidebars;
