/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  labs: [
    "labs/intro",
    {
      type: "category",
      label: "Labs",
      items: [
        "labs/hello-world/index",
        {
          type: "category",
          label: "JS & DOM Exercises (Lab)",
          items: [
            {
              type: "autogenerated",
              dirName: "labs/js-and-dom-exercises",
            }
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Assignments",
      items: [
        {
          type: "category",
          label: "Online Portfolio",
          items: [
            {
              type: "autogenerated",
              dirName: "labs/online-portfolio",
            }
          ],
        },
        {
          type: "category",
          label: "JS Exercises",
          items: [
            {
              type: "autogenerated",
              dirName: "labs/js-exercises",
            }
          ],
        },
        {
          type: "category",
          label: "Rock Paper Scissors",
          items: [
            {
              type: "autogenerated",
              dirName: "labs/rock-paper-scissors",
            }
          ],
        },
      ],
    },
  ],
  syllabus: [
    {
      type: `category`,
      label: `Syllabus`,
      items: [
        {
          type: "autogenerated",
          dirName: "syllabus",
        },
      ],
    },
  ],
  notes: [
    {
      type: `category`,
      label: `Notes`,
      collapsed: false,
      items: [
        "course-notes/index",
        "course-notes/git/index",
        "course-notes/dom-manipulation",
      ],
    }
  ]
};

module.exports = sidebars;
