/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  labs: [
    "labs/intro",
    "labs/hello-world/index",
    {
      type: "category",
      label: "1. Online Portfolio (Lab)",
      items: [
        {
          type: "autogenerated",
          dirName: "labs/online-portfolio",
        }
      ],
    },
    {
      type: "category",
      label: "2. Rock Paper Scissors",
      items: [
        {
          type: "autogenerated",
          dirName: "labs/rock-paper-scissors",
        }
      ],
    },
    // {
    //   type: "category",
    //   label: "Tutorials-basic",
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "labs/tutorial-basics",
    //     },
    //   ],
    // },
  ],
  syllabus: [
    {
      type: `category`,
      label: `Syllabus`,
      items: [
        {
          type: "autogenerated",
          dirName: "syllabus",
        },
      ],
    },
  ],
};

module.exports = sidebars;
